---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
language: en
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - /^\\s*```(.|\\n)+?^\\s*```/gm
      - /```[a-z]+(\n*[^`]*\n*)*```/gm
      - /\`.*\`/gm
      - /!?\[.+\]\(.+\)/gm
dictionaryDefinitions:
  - name: custom-dictionnary
    path: ./.cspell/custom-dictionnary.txt
dictionaries:
  - custom-dictionnary
words:
  - Seillama
flagWords:
  - hte
  - teh
caseSensitive: false
